version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"    # Port cho consumer trên host kết nối
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      # INTERNAL://kafka:29092 là listener cho Filebeat (trong Docker)
      # PLAINTEXT://localhost:9092 là listener cho consumer chạy trên host
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1 # Hoặc phiên bản bạn muốn
    container_name: filebeat
    user: root # Để Filebeat có quyền đọc file config và log
    volumes:
      # Mount file filebeat.yml từ thư mục gốc của host vào container
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # Mount file log.txt từ thư mục gốc của host vào container
      - ./log.txt:/var/log/app/log.txt:ro
    depends_on:
      - kafka
    command: filebeat -e -strict.perms=false # -e để log ra stdout

networks:
  default:
    name: kafka-filebeat-flat-network